(in-package "FUG5")

(defun compile-fug5 ()
  "Compile all files required by system fug5"
  (load "macros.l")
  (compile-file "vars.l")
  (compile-file "define.l")
  (compile-file "trace.l")
  (compile-file "generator.l")
  (compile-file "backtrack.l")
  (compile-file "external.l")
  (compile-file "fd-to-graph.l")
  (compile-file "determine.l")
  (compile-file "path.l")
  (compile-file "ignore.l")
  (compile-file "wait.l")
  (compile-file "alt.l")
  (compile-file "ralt.l")
  (compile-file "fset.l")
  (compile-file "control.l")
  (compile-file "type.l")
  (compile-file "pattern.l")
  (compile-file "findcset.l")
  (compile-file "graph.l")
  (compile-file "top.l")
  (compile-file "lexicon.l")
  (compile-file "linearize2.l")
  (compile-file "checker.l")
  (compile-file "complexity.l")
  (compile-file "fdlist.l")
  (compile-file "continue.l")
  (compile-file "test.l")
  (compile-file "psgraph.l")
  (load-fug5))

(defun load-fug5 ()
  "Load all files of system in right order"
  (load "macros.l")
  (load "vars")
  (load "define")
  (load "generator")
  (load "trace")
  (load "backtrack")
  (load "external")
  (load "path")
  (load "fd-to-graph")
  (load "determine")
  (load "lexicon")
  (load "linearize2")
  (load "pattern")
  (load "ignore")
  (load "wait")
  (load "alt")
  (load "ralt")
  (load "fset")
  (load "control")
  (load "type")
  (load "findcset")
  (load "graph")
  (load "top")
  (load "complexity")
  (load "fdlist")
  (load "continue")
  (load "checker")
  (load "test"))